# Generated by Django 5.0.3 on 2024-04-15 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("googledriveapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.BinaryField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="googledriveapp.file",
                    ),
                ),
            ],
        ),
    ]
