# Generated by Django 5.0.3 on 2024-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("googledriveapp", "0003_alter_file_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="page_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
