# Generated by Django 5.0.3 on 2024-05-02 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("googledriveapp", "0004_file_page_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="page_count",
        ),
    ]
